name: Reusable Commit Message Linter

on:
  pull_request:
    types: [opened, synchronize, edited]
  push:
    branches:
      - main
      - master
      - develop
      - feature/**
      - release/**

jobs:
  lint-commits:
    uses: gouef/github-lib-template/.github/workflows/commit-lint.yml@main